services:
  # Backend API Service
  - type: web
    name: flash-api
    env: python
    buildCommand: "pip install -r requirements_production.txt"
    startCommand: "python api_server_unified.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8001
      - key: HOST
        value: 0.0.0.0
      - key: WORKERS
        value: 1
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: API_KEYS
        value: "demo-key-123"
      - key: DB_HOST
        value: localhost
      - key: DB_NAME
        value: flash.db
      - key: REDIS_HOST
        value: none
      - key: MODEL_CACHE_ENABLED
        value: true
    
databases:
  - name: flash-db
    databaseName: flash
    user: flash
    plan: free